import type { Metadata } from 'next'
import { SUSE } from 'next/font/google'
import './globals.css'

const suse = SUSE({
	variable: '--font-suse',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${suse.variable} antialiased`}>{children}</body>
		</html>
	)
}
